# Generated by Django 5.2.16 on 2026-07-31 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='availability_status',
            field=models.BooleanField(default=True),
        ),
    ]
